--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2023-11-06 13:58:36

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'WIN1251';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- TOC entry 4896 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- TOC entry 238 (class 1255 OID 17187)
-- Name: filldepartmentshistory(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.filldepartmentshistory() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
	if tg_op  in ('UPDATE', 'INSERT')
		then 
			if tg_op = 'UPDATE' AND new.id <> old.id
				then raise exception 'Bad update!';
			end if;
			insert into departments_history ("action", id, "name", city_id, city_name, address, boss_id, boss_name)
					values (
						tg_op,
						new.id, 
						new."name", 
						new.city_id,
						(select "name" as city_name from public.cities where id = new.city_id),
						new.address,
						new.boss_id,
						(select concat(lastname, ' ', firstname) as boss_name from public.employees where id = new.boss_id)
					);
	elseif tg_op = 'DELETE'
		then
			insert into departments_history ("action", id, "name", city_id, city_name, address, boss_id, boss_name)
					values (
						tg_op,
						old.id, 
						old."name", 
						old.city_id,
						(select "name" as city_name from public.cities where id = old.city_id),
						old.address,
						old.boss_id,
						(select concat(lastname, ' ', firstname) as boss_name from public.employees where id = old.boss_id)
					);
	end if;
	return new;
end;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 17145)
-- Name: career; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.career (
    id integer NOT NULL,
    emp_id integer,
    city_id integer,
    address character varying,
    dep_id integer,
    boss_id integer,
    position_id integer,
    datestart date,
    dateend date,
    salary integer
);


--
-- TOC entry 223 (class 1259 OID 17144)
-- Name: career_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.career ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.career_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 17086)
-- Name: cities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cities (
    id integer NOT NULL,
    name character varying
);


--
-- TOC entry 217 (class 1259 OID 17085)
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17102)
-- Name: departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departments (
    id integer NOT NULL,
    name character varying,
    city_id integer,
    address character varying,
    boss_id integer
);


--
-- TOC entry 226 (class 1259 OID 17178)
-- Name: departments_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departments_history (
    history_id integer NOT NULL,
    action character varying,
    id integer,
    name character varying,
    city_id integer,
    city_name character varying,
    address character varying,
    boss_id integer,
    boss_name character varying
);


--
-- TOC entry 221 (class 1259 OID 17101)
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 17177)
-- Name: depatments_history_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departments_history ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.depatments_history_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 17075)
-- Name: employees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employees (
    lastname character varying,
    firstname character varying,
    email character varying NOT NULL,
    birthdate date,
    id integer NOT NULL
);


--
-- TOC entry 215 (class 1259 OID 17074)
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17094)
-- Name: positions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.positions (
    id integer NOT NULL,
    name character varying
);


--
-- TOC entry 219 (class 1259 OID 17093)
-- Name: positions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4888 (class 0 OID 17145)
-- Dependencies: 224
-- Data for Name: career; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.career (id, emp_id, city_id, address, dep_id, boss_id, position_id, datestart, dateend, salary) FROM stdin;
\.


--
-- TOC entry 4882 (class 0 OID 17086)
-- Dependencies: 218
-- Data for Name: cities; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cities (id, name) FROM stdin;
1	Kiev
2	Moscow
\.


--
-- TOC entry 4886 (class 0 OID 17102)
-- Dependencies: 222
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.departments (id, name, city_id, address, boss_id) FROM stdin;
2	Designers	\N	\N	\N
3	Developers	1	Independece square 2	1
1	The first department	1	Independece square 1	1
4	Developers	2	Red square 1	1
\.


--
-- TOC entry 4890 (class 0 OID 17178)
-- Dependencies: 226
-- Data for Name: departments_history; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.departments_history (history_id, action, id, name, city_id, city_name, address, boss_id, boss_name) FROM stdin;
5	INSERT	1	The first department	1	Kiev	Independece square 1	1	Test Test
6	UPDATE	1	The first department	1	Kiev	Independece square 1	1	Test Test
9	INSERT	4	Developers	1	Kiev	Independece square 2	1	Test Test
10	UPDATE	4	Developers	2	Moscow	Red square 1	1	Test Test
11	DELETE	4	Developers	2	Moscow	Red square 1	1	Test Test
\.


--
-- TOC entry 4880 (class 0 OID 17075)
-- Dependencies: 216
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.employees (lastname, firstname, email, birthdate, id) FROM stdin;
Test	Test	test@test.ru	1991-04-08	1
\.


--
-- TOC entry 4884 (class 0 OID 17094)
-- Dependencies: 220
-- Data for Name: positions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.positions (id, name) FROM stdin;
1	Programmer
2	DevOps
\.


--
-- TOC entry 4897 (class 0 OID 0)
-- Dependencies: 223
-- Name: career_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.career_id_seq', 1, false);


--
-- TOC entry 4898 (class 0 OID 0)
-- Dependencies: 217
-- Name: cities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cities_id_seq', 1, false);


--
-- TOC entry 4899 (class 0 OID 0)
-- Dependencies: 221
-- Name: departments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.departments_id_seq', 1, true);


--
-- TOC entry 4900 (class 0 OID 0)
-- Dependencies: 225
-- Name: depatments_history_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.depatments_history_history_id_seq', 11, true);


--
-- TOC entry 4901 (class 0 OID 0)
-- Dependencies: 215
-- Name: employees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.employees_id_seq', 1, false);


--
-- TOC entry 4902 (class 0 OID 0)
-- Dependencies: 219
-- Name: positions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.positions_id_seq', 1, false);


--
-- TOC entry 4725 (class 2606 OID 17151)
-- Name: career career_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.career
    ADD CONSTRAINT career_pk PRIMARY KEY (id);


--
-- TOC entry 4719 (class 2606 OID 17092)
-- Name: cities cities_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pk PRIMARY KEY (id);


--
-- TOC entry 4723 (class 2606 OID 17108)
-- Name: departments departments_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pk PRIMARY KEY (id);


--
-- TOC entry 4727 (class 2606 OID 17184)
-- Name: departments_history depatments_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments_history
    ADD CONSTRAINT depatments_history_pk PRIMARY KEY (history_id);


--
-- TOC entry 4715 (class 2606 OID 17081)
-- Name: employees employees_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pk PRIMARY KEY (id);


--
-- TOC entry 4717 (class 2606 OID 17083)
-- Name: employees employees_un; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_un UNIQUE (email);


--
-- TOC entry 4721 (class 2606 OID 17100)
-- Name: positions positions_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT positions_pk PRIMARY KEY (id);


--
-- TOC entry 4735 (class 2620 OID 17188)
-- Name: departments writedepartmenthistory; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER writedepartmenthistory BEFORE INSERT OR DELETE OR UPDATE ON public.departments FOR EACH ROW EXECUTE FUNCTION public.filldepartmentshistory();


--
-- TOC entry 4730 (class 2606 OID 17167)
-- Name: career career_fk_boss; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.career
    ADD CONSTRAINT career_fk_boss FOREIGN KEY (boss_id) REFERENCES public.employees(id) ON UPDATE CASCADE;


--
-- TOC entry 4731 (class 2606 OID 17152)
-- Name: career career_fk_city; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.career
    ADD CONSTRAINT career_fk_city FOREIGN KEY (city_id) REFERENCES public.cities(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 4732 (class 2606 OID 17157)
-- Name: career career_fk_dep; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.career
    ADD CONSTRAINT career_fk_dep FOREIGN KEY (dep_id) REFERENCES public.departments(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 4733 (class 2606 OID 17162)
-- Name: career career_fk_emp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.career
    ADD CONSTRAINT career_fk_emp FOREIGN KEY (emp_id) REFERENCES public.employees(id) ON UPDATE CASCADE;


--
-- TOC entry 4734 (class 2606 OID 17172)
-- Name: career career_fk_pos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.career
    ADD CONSTRAINT career_fk_pos FOREIGN KEY (position_id) REFERENCES public.positions(id) ON UPDATE CASCADE;


--
-- TOC entry 4728 (class 2606 OID 17139)
-- Name: departments departments_fk_boss; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_fk_boss FOREIGN KEY (boss_id) REFERENCES public.employees(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 4729 (class 2606 OID 17134)
-- Name: departments departments_fk_city; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_fk_city FOREIGN KEY (city_id) REFERENCES public.cities(id) ON UPDATE CASCADE ON DELETE SET NULL;


-- Completed on 2023-11-06 13:58:37

--
-- PostgreSQL database dump complete
--

